name: Deploy to Heroku

on:
  # Se activa cuando se hace push directo a main/master
  push:
    branches: [ main, master ]
  
  # O cuando el workflow de pruebas en PR se completa exitosamente
  workflow_run:
    workflows: ["Test Pull Request"]
    types: [completed]
    branches: [main, master]

jobs:
  build-and-deploy:
    # Solo ejecutar si es un push directo o si el workflow de pruebas fue exitoso
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      
      # Primero verificamos si la aplicación existe, si no, la creamos
      - name: Verify Heroku app exists
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          if ! heroku apps:info --app ${{ secrets.HEROKU_APP_NAME }} &> /dev/null; then
            echo "App does not exist, creating it"
            heroku apps:create ${{ secrets.HEROKU_APP_NAME }}
          else
            echo "App exists, continuing"
          fi
      
      # Configurar el stack a container primero
      - name: Set Heroku stack to container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku stack:set container --app ${{ secrets.HEROKU_APP_NAME }}
      
      # Iniciar sesión en el registro de contenedores de Heroku
      - name: Log in to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
      
      # Construir y enviar la imagen directamente al registro de Heroku
      - name: Build and push Docker image to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}
      
      # Liberar la imagen para desplegarla
      - name: Release to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
